const SHOPPER_VOCABULARY = [
  { id: 1, sectionId: "watch", sectionTitle: "Watch and Talk", word: "allowance", meaning: "용돈, 수당" },
  { id: 2, sectionId: "watch", sectionTitle: "Watch and Talk", word: "delicious", meaning: "맛있는" },
  { id: 3, sectionId: "watch", sectionTitle: "Watch and Talk", word: "discount", meaning: "할인" },
  { id: 4, sectionId: "watch", sectionTitle: "Watch and Talk", word: "expensive", meaning: "비싼" },
  { id: 5, sectionId: "watch", sectionTitle: "Watch and Talk", word: "fan", meaning: "부채; 선풍기; 팬" },
  { id: 6, sectionId: "watch", sectionTitle: "Watch and Talk", word: "item", meaning: "물품, 항목" },
  { id: 7, sectionId: "watch", sectionTitle: "Watch and Talk", word: "popular", meaning: "인기 있는" },
  { id: 8, sectionId: "watch", sectionTitle: "Watch and Talk", word: "price", meaning: "가격, 값" },
  { id: 9, sectionId: "watch", sectionTitle: "Watch and Talk", word: "receipt", meaning: "영수증" },
  { id: 10, sectionId: "watch", sectionTitle: "Watch and Talk", word: "salesperson", meaning: "판매원, 점원" },
  { id: 11, sectionId: "watch", sectionTitle: "Watch and Talk", word: "save", meaning: "저축하다" },
  { id: 12, sectionId: "watch", sectionTitle: "Watch and Talk", word: "souvenir", meaning: "기념품" },
  { id: 13, sectionId: "watch", sectionTitle: "Watch and Talk", word: "spend", meaning: "소비하다, 쓰다" },
  { id: 14, sectionId: "watch", sectionTitle: "Watch and Talk", word: "sweet", meaning: "달콤한, 단" },
  { id: 15, sectionId: "watch", sectionTitle: "Watch and Talk", word: "total", meaning: "합계, 총액" },
  { id: 16, sectionId: "watch", sectionTitle: "Watch and Talk", word: "traditional", meaning: "전통적인" },
  { id: 17, sectionId: "watch", sectionTitle: "Watch and Talk", word: "unique", meaning: "독특한, 특별한" },
  { id: 18, sectionId: "watch", sectionTitle: "Watch and Talk", word: "usually", meaning: "대개, 보통" },
  { id: 19, sectionId: "watch", sectionTitle: "Watch and Talk", word: "give ~ a discount", meaning: "~에게 할인을 해주다" },
  { id: 20, sectionId: "watch", sectionTitle: "Watch and Talk", word: "have a sale", meaning: "세일하다, 염가로 팔다" },
  { id: 21, sectionId: "watch", sectionTitle: "Watch and Talk", word: "keep a diary", meaning: "일기를 쓰다" },
  { id: 22, sectionId: "reading", sectionTitle: "Reading", word: "advice", meaning: "조언, 충고" },
  { id: 23, sectionId: "reading", sectionTitle: "Reading", word: "anchor", meaning: "닻; 닻을 내리다", definition: "a heavy object dropped into water to keep a ship in place" },
  { id: 24, sectionId: "reading", sectionTitle: "Reading", word: "budget", meaning: "예산", definition: "a plan for spending money" },
  { id: 25, sectionId: "reading", sectionTitle: "Reading", word: "decision", meaning: "결정" },
  { id: 26, sectionId: "reading", sectionTitle: "Reading", word: "effect", meaning: "효과", definition: "a change that happens because of an action or cause" },
  { id: 27, sectionId: "reading", sectionTitle: "Reading", word: "hot", meaning: "인기 있는, 뜨는" },
  { id: 28, sectionId: "reading", sectionTitle: "Reading", word: "hunger", meaning: "배고픔", definition: "the feeling when you need food" },
  { id: 29, sectionId: "reading", sectionTitle: "Reading", word: "influence", meaning: "영향을 주다, 영향", definition: "to make a change in someone or something" },
  { id: 30, sectionId: "reading", sectionTitle: "Reading", word: "information", meaning: "정보" },
  { id: 31, sectionId: "reading", sectionTitle: "Reading", word: "limited", meaning: "한정된, 제한된", definition: "having only a small number or amount" },
  { id: 32, sectionId: "reading", sectionTitle: "Reading", word: "lipstick", meaning: "립스틱" },
  { id: 33, sectionId: "reading", sectionTitle: "Reading", word: "miss", meaning: "놓치다; 그리워하다" },
  { id: 34, sectionId: "reading", sectionTitle: "Reading", word: "naturally", meaning: "자연스럽게, 당연히" },
  { id: 35, sectionId: "reading", sectionTitle: "Reading", word: "product", meaning: "상품, 제품", definition: "something that is made and sold" },
  { id: 36, sectionId: "reading", sectionTitle: "Reading", word: "rely", meaning: "의지하다, 믿다" },
  { id: 37, sectionId: "reading", sectionTitle: "Reading", word: "similar", meaning: "비슷한", definition: "almost the same but not exactly" },
  { id: 38, sectionId: "reading", sectionTitle: "Reading", word: "smart", meaning: "똑똑한" },
  { id: 39, sectionId: "reading", sectionTitle: "Reading", word: "sneakers", meaning: "스니커즈 운동화" },
  { id: 40, sectionId: "reading", sectionTitle: "Reading", word: "sound", meaning: "~처럼 들리다; 소리" },
  { id: 41, sectionId: "reading", sectionTitle: "Reading", word: "spread", meaning: "퍼지다", definition: "to move and cover a larger area" },
  { id: 42, sectionId: "reading", sectionTitle: "Reading", word: "strategy", meaning: "전략", definition: "a detailed plan to reach your goal" },
  { id: 43, sectionId: "reading", sectionTitle: "Reading", word: "viral", meaning: "급속히 퍼지는; 바이러스성의" },
  { id: 44, sectionId: "reading", sectionTitle: "Reading", word: "widely", meaning: "널리", definition: "by many people or in many places" },
  { id: 45, sectionId: "reading", sectionTitle: "Reading", word: "a piece of information", meaning: "정보 한 가지" },
  { id: 46, sectionId: "reading", sectionTitle: "Reading", word: "at a higher price", meaning: "더 비싼 가격에" },
  { id: 47, sectionId: "reading", sectionTitle: "Reading", word: "again and again", meaning: "반복해서, 되풀이해서" },
  { id: 48, sectionId: "reading", sectionTitle: "Reading", word: "fall for", meaning: "~에 속다, ~에 홀리다" },
  { id: 49, sectionId: "reading", sectionTitle: "Reading", word: "hold on", meaning: "기다려, 멈춰" },
  { id: 50, sectionId: "reading", sectionTitle: "Reading", word: "in one's case", meaning: "~의 경우에는" },
  { id: 51, sectionId: "reading", sectionTitle: "Reading", word: "on the Internet", meaning: "인터넷 상에서" },
  { id: 52, sectionId: "reading", sectionTitle: "Reading", word: "over one's budget", meaning: "예산을 초과한" },
  { id: 53, sectionId: "reading", sectionTitle: "Reading", word: "rely on", meaning: "~에 의존하다, ~에 기대다" },
  { id: 54, sectionId: "review", sectionTitle: "Review", word: "coin", meaning: "동전" },
  { id: 55, sectionId: "review", sectionTitle: "Review", word: "donate", meaning: "기부하다", definition: "to give money or things to help others" },
  { id: 56, sectionId: "review", sectionTitle: "Review", word: "star", meaning: "출연하다; 스타" },
  { id: 57, sectionId: "review", sectionTitle: "Review", word: "treadmill", meaning: "트레드밀" },
  { id: 58, sectionId: "review", sectionTitle: "Review", word: "be late for", meaning: "~에 늦다" },
  { id: 59, sectionId: "review", sectionTitle: "Review", word: "catch a cold", meaning: "감기에 걸리다" },
  { id: 60, sectionId: "review", sectionTitle: "Review", word: "look like", meaning: "~처럼 보이다" },
  { id: 61, sectionId: "review", sectionTitle: "Review", word: "make a donation", meaning: "기부하다, 기증하다" },
  { id: 62, sectionId: "review", sectionTitle: "Review", word: "make money", meaning: "돈을 벌다" },
  { id: 63, sectionId: "review", sectionTitle: "Review", word: "on one's own", meaning: "혼자서, 혼자 힘으로" },
  { id: 64, sectionId: "review", sectionTitle: "Review", word: "on sale", meaning: "할인·세일 중인" },
  { id: 65, sectionId: "review", sectionTitle: "Review", word: "talk on the phone", meaning: "통화하다" },
];

const STREET_ART_VOCABULARY = [
  { id: 1, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "street art", meaning: "거리 예술, 스트리트 아트" },
  { id: 2, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "come in", meaning: "~한 형태로 나오다" },
  { id: 3, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "form", meaning: "형태, 형식" },
  { id: 4, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "colorful", meaning: "다채로운, 화려한" },
  { id: 5, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "lively", meaning: "활기 찬, 생기 있는" },
  { id: 6, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "well-known", meaning: "잘 알려진, 유명한" },
  { id: 7, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "artwork", meaning: "예술 작품" },
  { id: 8, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "used to", meaning: "~하곤 했다 (과거의 습관)" },
  { id: 9, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "hip", meaning: "최신 유행의, 세련된" },
  { id: 10, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "piece of", meaning: "~의 작품(조각)" },
  { id: 11, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "over there", meaning: "저기" },
  { id: 12, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "be famous for", meaning: "~로 유명하다" },
  { id: 13, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "figure", meaning: "인물, 형상" },
  { id: 14, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "represent", meaning: "나타내다, 상징하다" },
  { id: 15, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "look closely at", meaning: "~을 자세히 살펴보다" },
  { id: 16, sectionId: "shoreditch", sectionTitle: "Shoreditch", word: "clue", meaning: "실마리, 단서" },
  { id: 17, sectionId: "banksy", sectionTitle: "Banksy", word: "social message", meaning: "사회적 메시지" },
  { id: 18, sectionId: "banksy", sectionTitle: "Banksy", word: "leafless", meaning: "잎이 없는" },
  { id: 19, sectionId: "banksy", sectionTitle: "Banksy", word: "spray", meaning: "뿌리다, 스프레이하다" },
  { id: 20, sectionId: "banksy", sectionTitle: "Banksy", word: "sprayer", meaning: "분무기, 스프레이" },
  { id: 21, sectionId: "banksy", sectionTitle: "Banksy", word: "opinion", meaning: "의견, 견해" },
  { id: 22, sectionId: "banksy", sectionTitle: "Banksy", word: "have a hard time", meaning: "힘든 시간을 보내다, 고생하다" },
  { id: 23, sectionId: "banksy", sectionTitle: "Banksy", word: "take care of", meaning: "~을 돌보다" },
  { id: 24, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "final stop", meaning: "마지막 정류장, 마지막 장소" },
  { id: 25, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "chewing gum", meaning: "껌" },
  { id: 26, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "be well known for", meaning: "~로 잘 알려져 있다" },
  { id: 27, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "drop", meaning: "떨어뜨리다, 버리다" },
  { id: 28, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "personal message", meaning: "개인적인 메시지" },
  { id: 29, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "loved one", meaning: "사랑하는 사람" },
  { id: 30, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "tiny", meaning: "아주 작은" },
  { id: 31, sectionId: "wilson", sectionTitle: "Ben Wilson", word: "pleasure", meaning: "기쁨, 즐거움" },
  { id: 32, sectionId: "grammar", sectionTitle: "Grammar", word: "make + O + adj.", meaning: "~을 …하게 만들다" },
  { id: 33, sectionId: "grammar", sectionTitle: "Grammar", word: "be going to", meaning: "~할 것이다" },
  { id: 34, sectionId: "grammar", sectionTitle: "Grammar", word: "one of the + 최상급 + 복수명사", meaning: "가장 ~한 것들 중 하나" },
  { id: 35, sectionId: "grammar", sectionTitle: "Grammar", word: "be famous for + -ing", meaning: "~하는 것으로 유명하다" },
  { id: 36, sectionId: "grammar", sectionTitle: "Grammar", word: "Noun + -less", meaning: "~이 없는 (leafless, hopeless 등)" },
  { id: 37, sectionId: "grammar", sectionTitle: "Grammar", word: "want + O + to-V", meaning: "~가 …하기를 원하다" },
];

const FREEDOM_VOCABULARY = [
  { id: 1, sectionId: "colonies", sectionTitle: "Colonies", word: "the Fourth of July", meaning: "미국 독립기념일 (7월 4일)" },
  { id: 2, sectionId: "colonies", sectionTitle: "Colonies", word: "colony", meaning: "식민지" },
  { id: 3, sectionId: "colonies", sectionTitle: "Colonies", word: "under the British rule", meaning: "영국의 통치 아래" },
  { id: 4, sectionId: "colonies", sectionTitle: "Colonies", word: "colonist", meaning: "식민지 주민" },
  { id: 5, sectionId: "colonies", sectionTitle: "Colonies", word: "tax", meaning: "세금" },
  { id: 6, sectionId: "colonies", sectionTitle: "Colonies", word: "have no voice", meaning: "발언권이 없다" },
  { id: 7, sectionId: "colonies", sectionTitle: "Colonies", word: "movement", meaning: "운동, 움직임" },
  { id: 8, sectionId: "colonies", sectionTitle: "Colonies", word: "spread widely", meaning: "널리 퍼지다" },
  { id: 9, sectionId: "colonies", sectionTitle: "Colonies", word: "independent", meaning: "독립적인" },
  { id: 10, sectionId: "washington", sectionTitle: "Washington", word: "leader", meaning: "지도자, 지휘관" },
  { id: 11, sectionId: "washington", sectionTitle: "Washington", word: "freedom", meaning: "자유" },
  { id: 12, sectionId: "washington", sectionTitle: "Washington", word: "fight against", meaning: "~와 싸우다" },
  { id: 13, sectionId: "washington", sectionTitle: "Washington", word: "have a hard time", meaning: "힘든 시간을 보내다" },
  { id: 14, sectionId: "washington", sectionTitle: "Washington", word: "give up", meaning: "포기하다" },
  { id: 15, sectionId: "washington", sectionTitle: "Washington", word: "trust", meaning: "믿다, 신뢰하다" },
  { id: 16, sectionId: "declaration", sectionTitle: "Declaration", word: "adopt", meaning: "채택하다" },
  { id: 17, sectionId: "declaration", sectionTitle: "Declaration", word: "Declaration of Independence", meaning: "독립선언서" },
  { id: 18, sectionId: "declaration", sectionTitle: "Declaration", word: "historic", meaning: "역사적인" },
  { id: 19, sectionId: "declaration", sectionTitle: "Declaration", word: "document", meaning: "문서" },
  { id: 20, sectionId: "declaration", sectionTitle: "Declaration", word: "announce", meaning: "발표하다, 선언하다" },
  { id: 21, sectionId: "declaration", sectionTitle: "Declaration", word: "unbelievable", meaning: "믿을 수 없는" },
  { id: 22, sectionId: "franklin", sectionTitle: "Franklin", word: "support", meaning: "지지하다, 지원" },
  { id: 23, sectionId: "franklin", sectionTitle: "Franklin", word: "hide", meaning: "숨기다" },
  { id: 24, sectionId: "franklin", sectionTitle: "Franklin", word: "watchful eyes", meaning: "감시의 눈" },
  { id: 25, sectionId: "franklin", sectionTitle: "Franklin", word: "spy", meaning: "스파이, 첩자" },
  { id: 26, sectionId: "independence", sectionTitle: "Independence", word: "defeat", meaning: "패배" },
  { id: 27, sectionId: "independence", sectionTitle: "Independence", word: "recognize", meaning: "인정하다" },
  { id: 28, sectionId: "independence", sectionTitle: "Independence", word: "Treaty of Paris", meaning: "파리 조약" },
  { id: 29, sectionId: "independence", sectionTitle: "Independence", word: "president", meaning: "대통령" },
  { id: 30, sectionId: "independence", sectionTitle: "Independence", word: "bury", meaning: "묻다, 매장하다" },
  { id: 31, sectionId: "independence", sectionTitle: "Independence", word: "cemetery", meaning: "묘지" },
  { id: 32, sectionId: "celebration", sectionTitle: "Celebration", word: "celebrate", meaning: "축하하다, 기념하다" },
  { id: 33, sectionId: "celebration", sectionTitle: "Celebration", word: "barbecue", meaning: "바베큐" },
  { id: 34, sectionId: "celebration", sectionTitle: "Celebration", word: "parade", meaning: "퍼레이드, 행진" },
  { id: 35, sectionId: "celebration", sectionTitle: "Celebration", word: "float", meaning: "축제용 장식 차량" },
  { id: 36, sectionId: "celebration", sectionTitle: "Celebration", word: "fireworks", meaning: "불꽃놀이" },
];
