const SHOPPER_VOCABULARY = [
  { id: 1, sectionId: "watch", sectionTitle: "Watch and Talk", word: "allowance", meaning: "용돈, 수당" },
  { id: 2, sectionId: "watch", sectionTitle: "Watch and Talk", word: "delicious", meaning: "맛있는" },
  { id: 3, sectionId: "watch", sectionTitle: "Watch and Talk", word: "discount", meaning: "할인" },
  { id: 4, sectionId: "watch", sectionTitle: "Watch and Talk", word: "expensive", meaning: "비싼" },
  { id: 5, sectionId: "watch", sectionTitle: "Watch and Talk", word: "fan", meaning: "부채; 선풍기; 팬" },
  { id: 6, sectionId: "watch", sectionTitle: "Watch and Talk", word: "item", meaning: "물품, 항목" },
  { id: 7, sectionId: "watch", sectionTitle: "Watch and Talk", word: "popular", meaning: "인기 있는" },
  { id: 8, sectionId: "watch", sectionTitle: "Watch and Talk", word: "price", meaning: "가격, 값" },
  { id: 9, sectionId: "watch", sectionTitle: "Watch and Talk", word: "receipt", meaning: "영수증" },
  { id: 10, sectionId: "watch", sectionTitle: "Watch and Talk", word: "salesperson", meaning: "판매원, 점원" },
  { id: 11, sectionId: "watch", sectionTitle: "Watch and Talk", word: "save", meaning: "저축하다" },
  { id: 12, sectionId: "watch", sectionTitle: "Watch and Talk", word: "souvenir", meaning: "기념품" },
  { id: 13, sectionId: "watch", sectionTitle: "Watch and Talk", word: "spend", meaning: "소비하다, 쓰다" },
  { id: 14, sectionId: "watch", sectionTitle: "Watch and Talk", word: "sweet", meaning: "달콤한, 단" },
  { id: 15, sectionId: "watch", sectionTitle: "Watch and Talk", word: "total", meaning: "합계, 총액" },
  { id: 16, sectionId: "watch", sectionTitle: "Watch and Talk", word: "traditional", meaning: "전통적인" },
  { id: 17, sectionId: "watch", sectionTitle: "Watch and Talk", word: "unique", meaning: "독특한, 특별한" },
  { id: 18, sectionId: "watch", sectionTitle: "Watch and Talk", word: "usually", meaning: "대개, 보통" },
  { id: 19, sectionId: "watch", sectionTitle: "Watch and Talk", word: "give ~ a discount", meaning: "~에게 할인을 해주다" },
  { id: 20, sectionId: "watch", sectionTitle: "Watch and Talk", word: "have a sale", meaning: "세일하다, 염가로 팔다" },
  { id: 21, sectionId: "watch", sectionTitle: "Watch and Talk", word: "keep a diary", meaning: "일기를 쓰다" },
  { id: 22, sectionId: "reading", sectionTitle: "Reading", word: "advice", meaning: "조언, 충고" },
  { id: 23, sectionId: "reading", sectionTitle: "Reading", word: "anchor", meaning: "닻; 닻을 내리다", definition: "a heavy object dropped into water to keep a ship in place" },
  { id: 24, sectionId: "reading", sectionTitle: "Reading", word: "budget", meaning: "예산", definition: "a plan for spending money" },
  { id: 25, sectionId: "reading", sectionTitle: "Reading", word: "decision", meaning: "결정" },
  { id: 26, sectionId: "reading", sectionTitle: "Reading", word: "effect", meaning: "효과", definition: "a change that happens because of an action or cause" },
  { id: 27, sectionId: "reading", sectionTitle: "Reading", word: "hot", meaning: "인기 있는, 뜨는" },
  { id: 28, sectionId: "reading", sectionTitle: "Reading", word: "hunger", meaning: "배고픔", definition: "the feeling when you need food" },
  { id: 29, sectionId: "reading", sectionTitle: "Reading", word: "influence", meaning: "영향을 주다, 영향", definition: "to make a change in someone or something" },
  { id: 30, sectionId: "reading", sectionTitle: "Reading", word: "information", meaning: "정보" },
  { id: 31, sectionId: "reading", sectionTitle: "Reading", word: "limited", meaning: "한정된, 제한된", definition: "having only a small number or amount" },
  { id: 32, sectionId: "reading", sectionTitle: "Reading", word: "lipstick", meaning: "립스틱" },
  { id: 33, sectionId: "reading", sectionTitle: "Reading", word: "miss", meaning: "놓치다; 그리워하다" },
  { id: 34, sectionId: "reading", sectionTitle: "Reading", word: "naturally", meaning: "자연스럽게, 당연히" },
  { id: 35, sectionId: "reading", sectionTitle: "Reading", word: "product", meaning: "상품, 제품", definition: "something that is made and sold" },
  { id: 36, sectionId: "reading", sectionTitle: "Reading", word: "rely", meaning: "의지하다, 믿다" },
  { id: 37, sectionId: "reading", sectionTitle: "Reading", word: "similar", meaning: "비슷한", definition: "almost the same but not exactly" },
  { id: 38, sectionId: "reading", sectionTitle: "Reading", word: "smart", meaning: "똑똑한" },
  { id: 39, sectionId: "reading", sectionTitle: "Reading", word: "sneakers", meaning: "스니커즈 운동화" },
  { id: 40, sectionId: "reading", sectionTitle: "Reading", word: "sound", meaning: "~처럼 들리다; 소리" },
  { id: 41, sectionId: "reading", sectionTitle: "Reading", word: "spread", meaning: "퍼지다", definition: "to move and cover a larger area" },
  { id: 42, sectionId: "reading", sectionTitle: "Reading", word: "strategy", meaning: "전략", definition: "a detailed plan to reach your goal" },
  { id: 43, sectionId: "reading", sectionTitle: "Reading", word: "viral", meaning: "급속히 퍼지는; 바이러스성의" },
  { id: 44, sectionId: "reading", sectionTitle: "Reading", word: "widely", meaning: "널리", definition: "by many people or in many places" },
  { id: 45, sectionId: "reading", sectionTitle: "Reading", word: "a piece of information", meaning: "정보 한 가지" },
  { id: 46, sectionId: "reading", sectionTitle: "Reading", word: "at a higher price", meaning: "더 비싼 가격에" },
  { id: 47, sectionId: "reading", sectionTitle: "Reading", word: "again and again", meaning: "반복해서, 되풀이해서" },
  { id: 48, sectionId: "reading", sectionTitle: "Reading", word: "fall for", meaning: "~에 속다, ~에 홀리다" },
  { id: 49, sectionId: "reading", sectionTitle: "Reading", word: "hold on", meaning: "기다려, 멈춰" },
  { id: 50, sectionId: "reading", sectionTitle: "Reading", word: "in one's case", meaning: "~의 경우에는" },
  { id: 51, sectionId: "reading", sectionTitle: "Reading", word: "on the Internet", meaning: "인터넷 상에서" },
  { id: 52, sectionId: "reading", sectionTitle: "Reading", word: "over one's budget", meaning: "예산을 초과한" },
  { id: 53, sectionId: "reading", sectionTitle: "Reading", word: "rely on", meaning: "~에 의존하다, ~에 기대다" },
  { id: 54, sectionId: "review", sectionTitle: "Review", word: "coin", meaning: "동전" },
  { id: 55, sectionId: "review", sectionTitle: "Review", word: "donate", meaning: "기부하다", definition: "to give money or things to help others" },
  { id: 56, sectionId: "review", sectionTitle: "Review", word: "star", meaning: "출연하다; 스타" },
  { id: 57, sectionId: "review", sectionTitle: "Review", word: "treadmill", meaning: "트레드밀" },
  { id: 58, sectionId: "review", sectionTitle: "Review", word: "be late for", meaning: "~에 늦다" },
  { id: 59, sectionId: "review", sectionTitle: "Review", word: "catch a cold", meaning: "감기에 걸리다" },
  { id: 60, sectionId: "review", sectionTitle: "Review", word: "look like", meaning: "~처럼 보이다" },
  { id: 61, sectionId: "review", sectionTitle: "Review", word: "make a donation", meaning: "기부하다, 기증하다" },
  { id: 62, sectionId: "review", sectionTitle: "Review", word: "make money", meaning: "돈을 벌다" },
  { id: 63, sectionId: "review", sectionTitle: "Review", word: "on one's own", meaning: "혼자서, 혼자 힘으로" },
  { id: 64, sectionId: "review", sectionTitle: "Review", word: "on sale", meaning: "할인·세일 중인" },
  { id: 65, sectionId: "review", sectionTitle: "Review", word: "talk on the phone", meaning: "통화하다" },
];
